### ISSUE TITLE
Non cuboid plots not rendered

### ISSUE THREAD

**Issue by TNTUP** [boy0001/plot2dynmap#1]
I tried to render a T N T plot claims but it doesn't work what I've expected:

http://i.qcfb.ca/20151116031121.png

PS: The dynmap was rendering at this time of writing.

Somewhere in my Creative world, A "L" plot looks bad... It seems like someone's claimed a road! But it isn't..

http://i.qcfb.ca/20151116031250.png

Using P2 v3.2.15 w/ P2D 3.2.0

PS: I don't know if I got ignored on P2D SpigotMC ressource, no answers.

**Comment by boy0001** [comment]
Duplicate of:
https://github.com/IntellectualSites/PlotSquared/issues/723

**Comment by TNTUP** [comment]
Oi I thought it was P2D issue, sorry!
